# Generated by Django 4.1 on 2022-10-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('city', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=300)),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
    ]
