# Generated by Django 4.1 on 2022-08-31 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='updated_at',
        ),
    ]
