# Generated by Django 4.1 on 2022-08-31 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_remove_provider_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
