# Generated by Django 4.1 on 2022-09-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
