# Generated by Django 4.1 on 2022-10-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='avans',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='cost_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='rest_de_plata',
            field=models.FloatField(),
        ),
    ]
