# Generated by Django 4.1 on 2022-10-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_budget_avans_alter_budget_cost_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='rest_de_plata',
            field=models.FloatField(default=0),
        ),
    ]
