# Generated by Django 4.1 on 2022-09-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_todolist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
