# Generated by Django 4.1 on 2022-10-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userextend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextend',
            name='user',
        ),
    ]
